# Don't print a new line at the start of the prompt
add_newline = false
# Pipes â•°â”€ â•­â”€
# Powerline symbols Â î‚° î‚± î‚² î‚³ î‚´ î‚µ î‚¶ î‚· î‚¸ î‚¹ î‚º î‚» î‚¼ î‚½ î‚¾ î‚¿ îƒ€ îƒ îƒ‚ îƒƒ îƒ„ îƒ… îƒ† îƒ‡ îƒˆ îƒŠ  îƒŒ îƒ îƒ îƒ îƒ îƒ‘ îƒ” îƒ’
# Wedges ğŸ­§ğŸ­’ ğŸ­£ğŸ­§ğŸ­“
# Random noise ğŸ¬–ğŸ¬¥ğŸ¬”ğŸ¬—
# Cool stuff ó°œ¥ î©± ï‹ ï€

# format = """
# $cmd_duration$username$hostname $directory $git_branch
# $character
# """
format = """
$os$username$hostname ó°œ¥ $directory \
ó°œ¥ $cmd_duration$status$c$dotnet$haxe$lua$rust$zig$dart$golang$nodejs$php$java$kotlin$haskell$python$docker_context[î‚´](fg:prev_bg)\
$git_branch
$character
"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[  î©± ï‹](bold fg:blue)"
error_symbol = "[  ï€ ï‹](bold fg:red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
style = "bg: sky"
symbol = "ó°˜¬"
truncation_length = 12
truncation_symbol = ""
format = " ó°œ¥ [î‚¶](bold fg:sky)[$symbol $branch(:$remote_branch)](fg:crust bg:sky)[î‚´ ](bold fg:sky)"

[git_commit]
commit_hash_length = 4
tag_symbol = "ï’¶ "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"

[git_status]
conflicted = " ğŸ³ "
ahead = " ğŸğŸ’¨ "
behind = " ğŸ˜° "
diverged = " ğŸ˜µ "
untracked = " ğŸ¤· â€"
stashed = " ğŸ“¦ "
modified = " ğŸ“ "
staged = '[++\($count\)](green)'
renamed = " âœï¸ "
deleted = " ğŸ—‘ "

[line_break]
disabled = false

[memory_usage]
disabled = true
threshold = -1
symbol = " "
style = "bold dimmed green"

[time]
disabled = true
format = 'ğŸ•™[\[ $time \]]($style) '
time_format = "%T"

[username]
style_user = "sky"
style_root = "red"
format = "[î‚´](fg:prev_bg bg:$style)[ $user](bold fg:crust bg:$style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format =  "[â€¢$hostname](bold bg:prev_bg fg:crust)[î‚´](fg:prev_bg)"
trim_at = ".companyname.com"
disabled = false

[directory]
home_symbol = " ï‘­ "
read_only = " ï‘– "
style = "bg:green fg:crust"
truncation_length = 3
truncation_symbol = " â€¢â€¢/"
format = '[î‚¶](bold fg:green)(bold fg:green)[ó°‰‹ $path]($style)[î‚´](bold fg:green)'

[directory.substitutions]
"Desktop" = " ï’© "
"Documents" = " ï’¥ "
"Downloads" = " ï‰ "
"Music" = " ó°ˆ "
"Pictures" = " ï "
"Videos" = " ï”¬ "
"GitHub" = " ó°Š¤ "

[cmd_duration]
min_time = 0
format = '[î‚¶](bold fg:yellow)[ó°ª¢ $duration](bold bg:yellow fg:crust)'

[status]
disabled = false
style = "yellow"
symbol = "ï€ "
failure_style = "red"
success_symbol = "ï€Œ "
success_style = "green"
not_executable_symbol = "îª‡ "
not_found_symbol = "ï€‚ "
format = "[î‚´](fg:prev_bg bg:$style)[ $symbol](fg:crust bg:$style)"

[os]
disabled = false
style = "surface0"
format = "[î‚¶]($style)[$symbol](fg:text bg:$style)"

[os.symbols]
AlmaLinux = "ïŒ "
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "îœ "
Arch = "ó°£‡ "
Artix = "ïŒŸ "
CentOS = "ïŒ„ "
Debian = "ó°£š "
EndeavourOS = "ïŒ¢ "
Fedora = "ó°£› "
FreeBSD = "ïŒŒ "
Garuda = "ïŒ· "
Gentoo = "ó°£¨ "
Illumos = "ïŒ¦ "
Kali = "ïŒ§ "
Linux = "ó°Œ½ "
Macos = "ó°€µ "
Manjaro = "ïŒ’ "
Mint = "ó°£­ "
NixOS = "ïŒ“ "
Nobara = "ï€ "
OpenBSD = "ïŒ¨ "
OracleLinux = "î¡™ "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ó±„› "
RedHatEnterprise = "ó±„› "
RockyLinux = "ïŒ« "
Solus = "ïŒ­ "
SUSE = "ïŒ” "
Ubuntu = "ó°•ˆ "
Unknown = "ï™ "
Void = "ïŒ® "
Windows = "ó°² "

[bun]
symbol = "î¯ "
style = "rosewater"
format = '[î‚´](fg:prev_bg bg:$style)[ $symbol($version)](fg:crust bg:$style)[î‚´](fg:$style bg:$style)'

[nodejs]
symbol = "îœ˜"
style = "green"
format = '[î‚´](fg:prev_bg bg:$style)[ $symbol($version)](fg:crust bg:$style)[î‚´](fg:$style bg:$style)'

[c]
symbol = "î˜ "
style = "lavender"
format = '[î‚´](fg:prev_bg bg:$style)[ $symbol($version)](fg:crust bg:$style)[î‚´](fg:$style bg:$style)'

[dotnet]
symbol = "î¿ "
style = "mauve"
format = '[î‚´](fg:prev_bg bg:$style)[ $symbol($version)](fg:crust bg:$style)[î‚´](fg:$style bg:$style)'

[haxe]
symbol = "îŸº "
style = "peach"
format = '[î‚´](fg:prev_bg bg:$style)[ $symbol($version)](fg:crust bg:$style)[î‚´](fg:$style bg:$style)'

[lua]
symbol = "î ¦ "
style = "blue"
format = '[î‚´](fg:prev_bg bg:$style)[ $symbol($version)](fg:crust bg:$style)[î‚´](fg:$style bg:$style)'

[zig]
symbol = "î£¯ "
style = "yellow"
format = '[î‚´](fg:prev_bg bg:$style)[ $symbol($version)](fg:crust bg:$style)[î‚´](fg:$style bg:$style)'

[dart]
symbol = "î˜ "
style = "sky"
format = '[î‚´](fg:prev_bg bg:$style)[ $symbol($version)](fg:crust bg:$style)[î‚´](fg:$style bg:$style)'

[rust]
symbol = "î¨"
style = "red"
format = '[î‚´](fg:prev_bg bg:$style)[ $symbol($version)](fg:crust bg:$style)[î‚´](fg:$style bg:$style)'

[golang]
symbol = "î˜§"
style = "blue"
format = '[î‚´](fg:prev_bg bg:$style)[ $symbol($version)](fg:crust bg:$style)[î‚´](fg:$style bg:$style)'

[php]
symbol = "î˜ˆ "
style = "mauve"
format = '[î‚´](fg:prev_bg bg:$style)[ $symbol($version)](fg:crust bg:$style)[î‚´](fg:$style bg:$style)'

[java]
symbol = "î‰– "
style = "peach"
format = '[î‚´](fg:prev_bg bg:$style)[ $symbol($version)](fg:crust bg:$style)[î‚´](fg:$style bg:$style)'

[kotlin]
symbol = "î˜´"
style = "mauve"
format = '[î‚´](fg:prev_bg bg:$style)[ $symbol($version)](fg:crust bg:$style)[î‚´](fg:$style bg:$style)'

[haskell]
symbol = "î˜Ÿ"
style = "mauve"
format = '[î‚´](fg:prev_bg bg:$style)[ $symbol($version)](fg:crust bg:$style)[î‚´](fg:$style bg:$style)'

[python]
symbol = "î˜† "
style = "green"
format = '[î‚´](fg:prev_bg bg:$style)[ $symbol($version)](fg:crust bg:$style)[î‚´](fg:$style bg:$style)'

[docker_context]
symbol = "ïŒˆ"
style = "blue"
format = '[î‚´](fg:prev_bg bg:$style)[ $symbol($context)](fg:crust bg:$style)[î‚´](fg:$style bg:$style)'
